title: Thawra
email:
description:
baseurl: ""
url:
twitter_username:
github_username:

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  episodes:
    output: true
