title: Thawra
email: 
description: Across hours of finely detailed inquiry, Daniel Denvir and Abdel Razzaq Takriti chart the emergence and evolution of revolutionary currents in the Mashriq, including nationalism, Nasserism, Ba'athism, communism, and Islamism-set in the context of imperialist power politics and predation.
baseurl: ""
url: 
twitter_username:
github_username:

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  episodes:
    output: true
